export const RATIO_PIXELS_TO_DEGREES = 2;
export const COUNT_OF_DEGREES_ON_AXIS = 20;
export const AXIS_Y_SIZE_IN_PIXELS = RATIO_PIXELS_TO_DEGREES * COUNT_OF_DEGREES_ON_AXIS;
export const FRAMES_PER_SECOND = 10;
